### ISSUE TITLE
pure python version of uamqp

### ISSUE THREAD

**Issue by JackyXu866** [Azure/azure-uamqp-python#166]
I am encountering several problems when cross-compiling this package because of the c file in it.
So I am wondering when will the pure python version be released?

**Comment by yunhaoling** [comment]
hey @JackyXu866 , thanks for reaching out.

The goods news is that we've started planning and prioritizing to get the ball rolling again on pure python library.

However there is plenty of work on feature parity and test remaining to be done and we have limited cycles and resources allocated on uamqp library right now.

I'll make sure in the coming months time and efforts would be put on pure python implementation, but there's no guaranteed timeline.

-----

And to help you out of the trouble, what kind of cross-compiling problems are you suffering from? I may know the solution or we could discuss.

**Comment by yunhaoling** [comment]
hey @JackyXu866 , hope you're keeping well!

are you a user of the azure-eventhub SDK? If you're an azure-eventhub user, then we have good news for you :)

I'm excited to announce that we redesigned our Python EventHubs SDK to not rely on any C code anymore, it’s now entirely implemented in Python [(5.8.0a3 - pypi)](https://pypi.org/project/azure-eventhub/5.8.0a3/). We’d love to get your feedback and perspective on this new version, as we believe you are using this SDK in an environment that would benefit from the changes.

Here are some highlights of the SDK :
•	Stability and robustness, eliminating any risks of C related memory leak or segmentation fault errors.
•	Full multi-platform support (ARM processors like M1, etc.)
•	Improved sending and receiving performance.

To get started, just install the wheel by command `pip install azure-eventhub==5.8.0a3` in your Python environment and you're all set to go with your applications. This package is fully backward compatible, and no changes are needed in your application.

We’re eager to hear what you think. Please reply to this thread at any time with feedback or any questions you have for us! We’re all ears.

**Comment by annatisch** [comment]
Thanks @simmel,
Indeed the intention is that the AMQP 1.0 implementation itself is going pure-python :)
While there will be a couple of Azure-specific features, the new library will follow the generic AMQP 1.0 specification.
However regarding the behaviour of the new library, one of our key considerations is backwards compatibility with our Azure SDKs (that is, compatibility with behaviour/errors/connection status/etc rather than API shape).
Therefore we've chosen to start the alpha of this library as a vendored package within our Azure EventHubs and ServiceBus SDKs while we get that early feedback before we publish it as a standalone package.

The pure-python version is being publicly developed is this branch:
https://github.com/Azure/azure-uamqp-python/tree/pyproto
So you are very welcome to install and try out from the repo until we reach a point where we are largely happy with the stability as the basis of our SDKs and can publish this to PyPI :)

**Comment by simmel** [comment]
Thank you @annatisch ! Dogfooding is always the best so it sounds like you're doing the right thing!

I'll try it out on some personal sideproject and let you know if I find something. Looks like the docs might not be up to date (at least the README) but the tests where up to date (and probably not even changed that much since you'll try to keep API compatibility) so I can start there.

Looking forward to having a Pure Python AMQP lib! That Microsoft would be the one to do it was not on my bingo card though ; )
