### ISSUE TITLE
reported performance issues

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-uamqp-python#38]
Context of this issue is using monitor-events via IoT extension.

We have some user reports that are experiencing very high CPU usage spikes (up to 100%)  - in this case when no messages are being received. The current implementation uses the ReceiveClientAsync.receive_messages_iter_async to poll messages.

I will add more details to this thread as I receive them (like verifying uAMQP version).

Thank you.

**Comment by annatisch** [comment]
Thanks @digimaun - I think this probably sums it up:
"in this case when no messages are being received"

In the case where no events are being received currently we just continuously work the connection in a loop without any kind of sleep. If messages are being received then this breaks up the workload - otherwise the Python process is just going 100% and will use up as much resources as that process is allowed (usually most of the core that it's running on).
https://github.com/Azure/azure-uamqp-python/blob/master/uamqp/async_ops/client_async.py#L932

I could put in here a tiny sleep - and though would likely be enough.. though it may impact performance a little. Something like:
```
while self.receiving and self._client._received_messages.empty():
    await asyncio.sleep(0.001)
    self.receiving = await self._client.do_work_async()
```

**Comment by annatisch** [comment]
CPU use on idle receive (i.e. no message throughput) and slow receive (low message throughput) should now be at reasonable levels with release 1.0.3.

CPU will remain quite high with high message throughput, as we prioritize message throughput performance over CPU consumption. In this scenario I would recommend using an external tool to limit the resources available to the process if there's a scenario where it must be kept to a minimum.

For anyone who is not interested in message throughput performance and wishes to slow down the message receiver in order to reduce CPU and memory load, you can do so by lowering the receiver prefetch value and receiving in small batches for processing.
